### ISSUE TITLE
Error signing up: "o.data is undefined"

### ISSUE THREAD

**Issue by elimisteve** [phrazzld/studymode#2] opened 2023-02-13 05:08 UTC
Interesting project! There are _much_ shorter paths through the knowledge graph for learning all sorts of things, and we need more attempts to rapidly find and popularize them :ok_hand: .

Screenshot of error when trying to sign up:

![studymode-signup-error-Screenshot_2023-02-12_21-07-08](https://user-images.githubusercontent.com/139603/218375347-3cfa4484-1645-4482-89f2-9157b86b675f.png)

**Comment by elimisteve** [comment] 2023-02-13 05:09
This is in Firefox btw. The JS console is empty.

**Comment by elimisteve** [comment] 2023-02-13 05:15
I tried signing up again and got this error, so I guess my signup succeeded but there was an error parsing the response from the server or something?

![studymode-signup-error2-Screenshot_2023-02-12_21-14-25](https://user-images.githubusercontent.com/139603/218376343-21454906-84fc-4e5e-8548-d1c0525a1483.png)

**Comment by moomooskycow** [comment] 2023-02-13 13:13
Thanks for taking a look at the project Steve! 

> There are much shorter paths through the knowledge graph for learning all sorts of things, and we need more attempts to rapidly find and popularize them 👌 .

Fully agree. The company I work for, Memre, does some pretty interesting stuff on the "optimize your personal review schedule" and "know what you know" side of things, and I think GPT and other generative AI projects enable effortless production of infinite learning content. The ultimate vision for all learning apps is pushbutton upload of any concept to your brain, Matrix style, and maybe this project can be a baby step in that direction.

It is super prototype alpha right now haha, so I appreciate you reporting the funk you run into. This issue is high priority -- sign up flow's gotta be smooth!

**Comment by moomooskycow** [comment] 2023-02-13 13:33
I couldn't reproduce the `o.data` error, but I did get a `createMemreUserResponseJson.data is undefined` issue that I just fixed. Also added a redirect in the auth component so that if you're already logged in you get sent back to the home page -- should address that confusing second state you sent over (i.e. something fails but it's recoverable and you're still stuck on the auth page thinking you don't have an account).

Change is deploying now (this is my first Next.js project, Next.js and Vercel are pretty rad). I'll do some more testing on prod to verify that the signup flow works as expected before closing this issue.

**Comment by moomooskycow** [comment] 2023-02-13 13:35
Ahh, even better: I don't have the MEMRE_API_KEY environment variable set on prod! That'll do it :P

**Comment by moomooskycow** [comment] 2023-02-13 13:40
Yup yup, should be working now 👍

**Closed as completed by moomooskycow** 2023-02-13 13:40 UTC
